//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemesignalR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SignalRDenemeEntities : DbContext
    {
        public SignalRDenemeEntities()
            : base("name=SignalRDenemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Musteri> tbl_Musteri { get; set; }
        public virtual DbSet<tbl_Sayac> tbl_Sayac { get; set; }
        public virtual DbSet<tbl_SayacHata> tbl_SayacHata { get; set; }
        public virtual DbSet<tbl_SayacHataLog> tbl_SayacHataLog { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual ObjectResult<string> callWebServices(Nullable<int> sayacid, Nullable<System.DateTime> tarih)
        {
            var sayacidParameter = sayacid.HasValue ?
                new ObjectParameter("sayacid", sayacid) :
                new ObjectParameter("sayacid", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("callWebServices", sayacidParameter, tarihParameter);
        }
    
        public virtual ObjectResult<sayacHata_Result> sayacHata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sayacHata_Result>("sayacHata");
        }
    
        public virtual ObjectResult<sayacHataIdProp_Result> sayacHataIdProp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sayacHataIdProp_Result>("sayacHataIdProp", idParameter);
        }
    }
}
