//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemesignalR
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Musteri
    {
        public int id { get; set; }
        public string Musteriad { get; set; }
        public string lat { get; set; }
        public string lang { get; set; }
        public string Sehir { get; set; }
    }
}
