//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemesignalR
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SayacHataLog
    {
        public int id { get; set; }
        public Nullable<int> SayacId { get; set; }
        public Nullable<int> Hataid { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
